# @package _global_
# make sure to include the above commented global setting!

# pipeline info
pipeline: CL_MAIN_EXPR
expr_name: fgadahat_cu_pmnist_20tasks
train_tasks: 20
eval_after_tasks: 20
global_seed: 1

# paradigm settings
cl_paradigm: TIL

# components
defaults:
  - /cl_dataset: permuted_mnist.yaml
  - /backbone: hat_mlp.yaml
  - /cl_algorithm: fgadahat.yaml
  - /optimizer: adam.yaml
  - /lr_scheduler: reduce_lr_on_plateau.yaml
  - /trainer: cpu.yaml
  - /metrics: hat_default.yaml
  - /lightning_loggers: default.yaml
  - /callbacks: cl_default.yaml
  - /hydra: default.yaml
  - /misc: default.yaml

# outputs
output_dir: outputs/${expr_name}/${misc.timestamp}

# overrides
cl_algorithm:
  importance_type: output_weight_abs_sum_x_activation_abs
  adjustment_intensity: 1.5e-07
  base_linear: 5
trainer:
  max_epochs: 2