_target_: clarena.cl_algorithms.AmnesiacHAT
buffer_size: 64
distillation_reg_factor: 0.5
replay_ce_factor: 0.5
adjustment_mode: adahat
adjustment_intensity: 1e-6
s_max: 400.0
clamp_threshold: 50
mask_sparsity_reg_factor: 0.1
mask_sparsity_reg_mode: "original"
task_embedding_init_mode: "N01"
epsilon: 0.1