_target_: clarena.cl_algorithms.FGAdaHAT
adjustment_intensity: 1.5e-7
importance_type: input_weight_gradient_abs_sum
importance_summing_strategy: add_all
importance_scheduler_type: linear_sparsity_reg
neuron_to_weight_importance_aggregation_mode: min
s_max: 400.0
clamp_threshold: 50
mask_sparsity_reg_factor: 0.1
mask_sparsity_reg_mode: "original"
base_importance: 1e-8
base_mask_sparsity_reg: 0.1
base_linear: 5
filter_by_cumulative_mask: false
filter_unmasked_importance: false
step_multiply_training_mask: true
task_embedding_init_mode: "N01"
