# @package _global_
# make sure to include the above commented global setting!

# evaluation info
pipeline: CUL_FULL_EVAL
dd_eval_tasks: 5
ad_eval_tasks: 5
global_seed: 1

# evaluation target
main_model_path: outputs/inpdendent_pmnist_5tasks/2026-01-08_10-31-09/saved_models/cl_model.pth
refretrain_model_path: outputs/inpdendent_pmnist_5tasks/2026-01-08_10-31-09/saved_models/cl_model.pth
reforiginal_model_path: outputs/inpdendent_pmnist_5tasks/2026-01-08_10-31-09/reforiginal/saved_models/cl_model.pth

# paradigm settings
cl_paradigm: TIL

# components
defaults: 
  - /cl_dataset: permuted_mnist.yaml
  - /trainer: cpu_eval.yaml
  - /metrics: cul_full_eval_default.yaml
  - /callbacks: eval_default.yaml
  - /hydra: default.yaml
  - /misc: default.yaml

# outputs
output_dir: outputs/inpdendent_pmnist_5tasks/2026-01-08_10-31-09/eval # output to the same folder as the experiment