# @package _global_
# make sure to include the above commented global setting!

# pipeline info
pipeline: STL_EXPR
expr_name: example_stl_expr
eval: true
global_seed: 1

# components
defaults:
  - /stl_dataset: mnist.yaml
  - /stl_algorithm: single_learning.yaml
  - /backbone: mlp.yaml
  - /optimizer: adam.yaml
  - /lr_scheduler: reduce_lr_on_plateau.yaml
  - /trainer: cpu.yaml
  - /metrics: stl_default.yaml
  - /lightning_loggers: default.yaml
  - /callbacks: stl_default.yaml
  - /hydra: default.yaml
  - /misc: default.yaml

# outputs
output_dir: outputs/${expr_name}/${misc.timestamp}

# overrides
trainer: 
  max_epochs: 2