# @package _global_
# make sure to include the above commented global setting!

# pipeline info
pipeline: CL_MAIN_EXPR
expr_name: independent
train_tasks: 10
eval_after_tasks: 10 
global_seed: 1

# paradigm settings
cl_paradigm: TIL

# components
defaults:
  - /cl_dataset: permuted_mnist.yaml
  - /cl_algorithm: independent.yaml
  - /backbone: clmlp.yaml
  - /optimizer: adam.yaml
  - /lr_scheduler: reduce_lr_on_plateau.yaml
  - /trainer: cpu.yaml
  - /metrics: cl_main_expr_default.yaml
  - /lightning_loggers: default.yaml
  - /callbacks: cl_default.yaml
  - /hydra: default.yaml
  - /misc: default.yaml

# outputs
output_dir: outputs/${expr_name}/${misc.timestamp}

# overrides
trainer:
  max_epochs: 2